### PR TITLE
check if value is set before accessing length

### PR DESCRIPTION
**Pull request by joejoejoew**

### CODE REVIEW

**Comment by kadikraman** [comment]
Hi @joejoejoew - thanks for your contribution!

Could you please add a test to highlight the necessity of this change? Cheers!

**Comment by joejoejoew** [comment]
Hi, here's a test. I also added a commit to fix a long line eslint was complaining about.

**Comment by kadikraman** [comment]
Thanks! Looks good to me 👍

**Comment by kadikraman** [comment]
Published your fix in `v0.1.4` 🎉

**Pull request merged**
