### PR TITLE
Ability to add custom markdownDict

### PR DESCRIPTION
**Pull request by slomek**
- custom markdownDict in `draftToMd(..)`
- custom inlineStyles and blockStyles in `mdToDraftjs(..)`
- fix ESLint issues

### CODE REVIEW

**Comment by kadikraman** [comment]
Hi @slomek - thanks for your contribution! Looks great! Although I think it might make more sense to have the passed in dictionary extend the defaults rather than replace it. So instead of an `or` statement, you'd have
```js
const markdownDict = { ...defaultMarkdownDict, ...mdDict };
```
So that if you choose to extend the default dictionary, you won't have to include the things already in it, but you'd still be able to override them if you wanted to.

**Comment by slomek** [comment]
Great point, I'll update my PR as soon as I find some time :)

**Comment by kadikraman** [comment]
Nice! Just one little thing, would you mind changing the `customMarkdownDict` in the test from

```js
const customMarkdownDict = {
  BOLD: '__',
  ITALIC: '*',
  STRIKETHROUGH: '~~'
};
```

to

```js
const customMarkdownDict = {
  BOLD: '**',
  STRIKETHROUGH: '~~'
};
```

so to use ** and instead for bold (still valid markdown).
And keep the tests, just update the one that tests for BOLD. This way we also test that the destructuring works as intended.

So the descriptions of the tests would be:
1) returns unstyled text correctly
2) returns text with an overridden style correctly
3) returns text with a default style correctly
4) returns text with an overridden style correctly

**Comment by slomek** [comment]
Thanks again for the feedback. Let me know if this is good enough ;)

**Pull request merged**
